version: '3'
services:
  jenkins:
    container_name: jenkins
    image: rms1000watt/jenkins-docker:latest
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
