pipeline {
    agent {
        docker {
            image 'docker:17.12.0-ce-git'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Build NodeJS') { 
            steps {
                sh("rm -rf dummy-nodejs-project && \
                    git clone https://github.com/rms1000watt/dummy-nodejs-project.git && \
                    cd dummy-nodejs-project && \
                    ./build.sh")
            }
        }
        stage('Build Golang') { 
            steps {
                sh("rm -rf dummy-golang-project && \
                    git clone https://github.com/rms1000watt/dummy-golang-project.git && \
                    cd dummy-golang-project && \
                    ./build.sh")
            }
        }
        stage('Test') { 
            steps {
                echo 'Testing Done'
            }
        }
    }
}
