pipeline {
    agent {
        docker {
            image 'alpine:latest'
        }
    }
    stages {
        stage('Build') { 
            steps {
                echo 'Building Done'
            }
        }
        stage('Test') { 
            steps {
                echo 'Testing Done'
            }
        }
    }
}
